# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fUJtZwhNxkEbjQSECpCMVwL0NVedrLS
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm1.png")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mexriniso.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("ffff.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mmmm.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("aa.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)